---
- name: Deploy spring Pet Clinic on Linux VM
  hosts: appserver
  become: yes
  vars: 
    java_package: openjdk-11-jdk
    appdir: /usr/share/springpetclinic
    app_jar_url: https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
    app_file_name: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
    app_user_name: springbootuser
    test_var : just for testing
  tasks:
    - name: Display Java package
      debug:
        var: java_package
    - name: Checking variables
      debug:
        var: test_var
    - name: Update ubuntu packages And install Open Jdk Java
      apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
    - name: Create Spring Pet Clinic Directory
      file:
        path: "{{ appdir }}"
        state: directory
    - name: Download spring-petclinic jar file
      get_url:
            url: "{{ app_jar_url }}"
            dest: "{{ app_file_name }}"
    - name: Create the user 'springbootuser'
      user:
        name: "{{ app_user_name }}"
        password: 1234567
        state: present
    - name: Change OwnerShip of Jar File Clinic
      file:
        path: "{{ app_file_name }}"
        owner: "{{ app_user_name }}"
        mode: '500'
        state: file
    - name: Copy file 'springpetclinic.service'
      copy:
        dest: /etc/systemd/system/springpetclinic.service
        src: springpetclinic.service
    - name: Enable And Start springpetclinic  service unit is running
      systemd:
        name: springpetclinic.service
        enabled: yes
        state: started