---
- name: Deploy spring Pet Clinic on Linux VM
  hosts: appserver
  become: yes
  tasks:
    - name: Update ubuntu packages And install Open Jdk Java
      apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: Create Spring Pet Clinic Directory
      file:
        path: /usr/share/springpetclinic
        state: directory
    - name: Download spring-petclinic jar file
      get_url:
            url: https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
            dest: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
    - name: Create the user 'springbootuser'
      user:
        name: springbootuser
        password: 1234567
        state: present
    - name: Change OwnerShip of Jar File Clinic
      file:
        path: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
        owner: springbootuser
        mode: '500'
        state: file