---
- name: Deploy spring Pet Clinic on Linux VM
  hosts: appserver
  become: yes
  tasks:
    # - name: Display Java package
    #   debug:
    #     var: java_package
    # - name: Checking variables var1
    #   debug:
    #     var: test_var1
    # - name: Checking variables var2
    #   debug:
    #     var: test_var2
    - name: fail the distribution if os is other than ubuntu and centos
      fail:
        msg: "this playbook will work only on ubuntu for other os  support will added soon "
      when: ansible_facts['distribution'] != "Ubuntu" and ansible_facts['distribution'] != "CentOS"
    - name: Update ubuntu packages And install Open Jdk Java
      apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
      notify:  debug msg for java
    - name: Create Spring Pet Clinic Directory
      file:
        path: "{{ appdir }}"
        state: directory
      notify: debug msg for Directory
    - name: Download spring-petclinic jar file
      get_url:
            url: "{{ app_jar_url }}"
            dest: "{{ app_file_name }}"
    - name: Create the user 'springbootuser'
      user:
        name: "{{ app_user_name }}"
        password: 1234567
        state: present
      notify: Change OwnerShip of Jar File Clinic
    - name: Copy file 'springpetclinic.service'
      copy:
        dest: /etc/systemd/system/springpetclinic.service
        src: springpetclinic.service
    - name: Enable And Start springpetclinic  service unit is running
      systemd:
        name: springpetclinic.service
        enabled: yes
        state: started
  handlers:
    - name: Change OwnerShip of Jar File Clinic
      file:
        path: "{{ app_file_name }}"
        owner: "{{ app_user_name }}"
        mode: '500'
        state: file

    - name: debug msg for java
      debug:
        msg: "java with package {{ java_package }} is installed"

    - name: debug msg for Directory
      debug:
        msg: "Pet Clinic  Directory is created at {{ appdir }}"